# Generated by Django 3.0.7 on 2022-09-20 04:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20220920_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='note',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 4, 18, 39, 952531, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 4, 18, 39, 952540, tzinfo=utc)),
        ),
    ]
